### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by okh4** [Project-Sloth/ps-loading#1]
after uncommenting q-parallax and commenting out q-carousel
screen stays black without video
![image](https://user-images.githubusercontent.com/71461029/154663670-b6d550fc-c616-43e5-bf64-f7f14730e397.png)
![image](https://user-images.githubusercontent.com/71461029/154665261-c8cda7d9-6051-4be3-aa06-14defed4c9c7.png)

**Comment by kokorog** [comment]
same

**Comment by loljoshie** [comment]
Haven't had that issue myself but I'll do some more investigating soon to see if I can recreate this report! Thanks!

**Comment by Krizmatic** [comment]
Same for me

**Comment by EXTN-Oxy** [comment]
also get the same :)
![image](https://user-images.githubusercontent.com/88489600/154875873-ee536f68-53a1-4181-b3fa-dea2aaf9404e.png)

**Comment by loljoshie** [comment]
Fixed and can now be found in the official QBCore Framework! Thanks!!
